### ISSUE TITLE
Script checks system default list of openssl ciphersuites

### ISSUE THREAD

**Issue by alexstuart** [mornau/starttls_ciphers#1]
Nice code, but line 179 gets the default list of ciphers to check from `openssl ciphers | tr ':' ' '`. Compare that list with `openssl ciphers 'ALL'` and `openssl ciphers 'ALL:COMPLEMENTOFALL'`

**Comment by mornau** [comment]
Sorry for never getting back to you there, Alex. You were and are perfectly right. 
I have not been using this script for a long time, but have just fixed it to at least work with current openssl (3.x). However, for now, it is limited (hardcoded) to TLS 1.2 (because the cipherspec changed for 1.3, and would require a major update)
